const REGISTRYADDRESS = process.env.REACT_APP_REGISTRYADDRESS;
const KAFKACONTROLLER = process.env.REACT_APP_KAFKACONTROLLER;
const KAFKAADDRESS = process.env.REACT_APP_KAFKAADDRESS;
const SECRET = process.env.REACT_APP_SECRET;
const VISITORINTERVAL = Number(process.env.REACT_APP_VISITORINTERVAL) * 1000 || 0.75 * 1000;
const SENSORCHECKINTERVAL = Number(process.env.REACT_APP_SENSORCHECKINTERVAL) || 5;
const SECRETAES = process.env.REACT_APP_SECRETAES || '11122233344455566677788822244455555555555555555231231321313aaaff'

console.log({ config: { REGISTRYADDRESS, KAFKAADDRESS, KAFKACONTROLLER, SECRET, VISITORINTERVAL, SENSORCHECKINTERVAL, SECRETAES } });

export { REGISTRYADDRESS, KAFKAADDRESS, KAFKACONTROLLER, SECRET, VISITORINTERVAL, SENSORCHECKINTERVAL, SECRETAES };