echo "REGISTRYADDRESS=$REGISTRYADDRESS" >> .env;
echo "KAFKACONTROLLER=$KAFKACONTROLLER" >> .env;
echo "KAFKAADDRESS=$KAFKAADDRESS" >> .env;
echo "SECRET=$SECRET" >> .env;
echo "$SECRET, $REGISTRYADDRESS, $KAFKACONTROLLER, $KAFKAADDRESS";